action: ??? # train or test
name: ??? # name of the experiment needed for the logs
split: ???
modality: ???
total_batch: 64 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
resume_from: null # checkpoint directory
logname: null # name of the logs
models_dir: null # directory containing all the models
split_path: 'action-net/step8-balance'
emg_path: 'emg/step7-merge'

# for emg -> total_batch: 64, batch_size: 32 
modalities:
  EMG:
    train: 
      num_iter: 20000 # number of training iterations with total_batch size
      lr_steps: 16000 # steps before reducing learning rate
      eval_freq: 25 # evaluation frequency

    test:
      num_clips: 1
    dataset: 
      annotations_path: train_val # path for the annotations data
      shift: nono # shifts of the dataset
      workers: 0 # number of workers for the dataloader
      stride: 2 # stride in case of dense sampling
      resolution: 224 # input resolution to the model
      data_path: emg # path to RGB data
      tmpl: "BOH" # format of RGB filenames
      features_name: test_feat_action
      agent: "SO4"

    models:
      EMG:
        name: "FinalClassifierEMG"
        normalize: False
        kwargs: {}
        lr: 0.05
        sgd_momentum: 0.9
        weight_decay: 1e-3
  RGB:
    train:
      num_iter: 5000 # number of training iterations with total_batch size
      lr_steps: 3000 # steps before reducing learning rate
      eval_freq: 50 # evaluation frequency
      num_clips: 1 # clips adopted in training
      dense_sampling: True
      num_frames_per_clip: 16

    test:
      num_clips: 5 
      dense_sampling: True
      num_frames_per_clip: 16

    dataset:
      annotations_path: train_val # path for the annotations data
      shift: ??? # shifts of the dataset
      workers: 0 # number of workers for the dataloader
      stride: 2 # stride in case of dense sampling
      resolution: 224 # input resolution to the model
      data_path: ??? # path to RGB data
      tmpl: "img_{:010d}.jpg" # format of RGB filenames
      features_name: test_feat_kinetics

    models:
      RGB:
        name: "LSTM"
        normalize: False
        kwargs: {}
        lr: 0.1
        sgd_momentum: 0.9
        weight_decay: 1e-7

  specto:
    train: 
      num_iter: 5000 # number of training iterations with total_batch size
      lr_steps: 3000 # steps before reducing learning rate
      eval_freq: 25 # evaluation frequency
      num_clips: 1

    test:
      num_clips: 1

    dataset: 
      annotations_path: train_val # path for the annotations data
      shift: nono # shifts of the dataset
      workers: 0 # number of workers for the dataloader
      stride: 2 # stride in case of dense sampling
      resolution: 224 # input resolution to the model
      data_path: ../spectograms # path to specto data
      tmpl: "BOH" # format of RGB filenames
      features_name: test_feat_action

    models:
      specto:
        name: "LeNet5"
        normalize: True
        kwargs: {}
        lr: 5e-3
        sgd_momentum: .98
        weight_decay: 1e-4
