action: ??? # train or test
name: ??? # name of the experiment needed for the logs
split: ???
modality: fusion
total_batch: 128 # total batch size if training is done with gradient accumulation
batch_size: 32 # batch size for the forward
gpus: null # gpus adopted
wandb_name: null # needed for wandb logging
resume_from: null # checkpoint directory
logname: null # name of the logs
models_dir: null # directory containing all the models
split_path: 'action-net/rgb-video'
emg_path: 'emg/step6-merge'

# for rgb -> split_path: action-net/rgb-video
# for emg -> total_batch: 128, batch_size: 32 
modalities:
  fusion:
    train: 
      num_iter: 5000 # number of training iterations with total_batch size
      lr_steps: 3000 # steps before reducing learning rate
      eval_freq: 50 # evaluation frequency

    test:
      num_clips: 1
    dataset: 
      annotations_path: train_val # path for the annotations data
      shift: nono # shifts of the dataset
      workers: 0 # number of workers for the dataloader
      stride: 2 # stride in case of dense sampling
      resolution: 224 # input resolution to the model
      data_path: emg # path to RGB data
      tmpl:  "img_{:010d}.jpg" # format of RGB filenames
      features_name: test_feat_action
      agent: "S04"

    models:
      fusion:
        name: "FusionClassifier"
        normalize: False
        kwargs: {}
        lr: 0.2
        sgd_momentum: 0.9
        weight_decay: 1e-4
